//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCartDetail
    {
        public int id { get; set; }
        public string BookName { get; set; }
        public int BookPrice { get; set; }
        public int BookQuantityUser { get; set; }
        public int BookUserId { get; set; }
    }
}
